// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TemporalTableWithNavigation
{
    public partial class Statuses
    {
        public Statuses()
        {
            Employees = new HashSet<Employees>();
        }

        public int Id { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Employees> Employees { get; set; }
    }
}